"""
glossary.py
-----------
Glossary of flower-part terms for the BIO262 dissection tool.

Each entry has a short definition, a diagram generated by the tool (in
glossary_images/), and a link to the relevant Wikipedia article, which carries
photos and fuller detail.
"""

WIKI = "https://en.wikipedia.org/wiki/"

GLOSSARY = [
    # ---- whole flower ----
    {"term": "Receptacle", "cat": "Whole flower", "image": "receptacle.png",
     "definition": "The receptacle is the tip of the flower stalk. All the floral "
                   "parts attach to it.",
     "wiki": WIKI + "Receptacle_(botany)"},

    # ---- calyx / corolla ----
    {"term": "Calyx", "cat": "Perianth", "image": "calyx.png",
     "definition": "The calyx is the outer whorl of the flower. It is made of all "
                   "the sepals.",
     "wiki": WIKI + "Sepal"},
    {"term": "Sepal", "cat": "Perianth", "image": "sepal.png",
     "definition": "A sepal is one segment of the calyx. Sepals are often green and "
                   "protect the bud.",
     "wiki": WIKI + "Sepal"},
    {"term": "Corolla", "cat": "Perianth", "image": "corolla.png",
     "definition": "The corolla is the whorl of petals. It is usually the showy "
                   "coloured part that attracts pollinators.",
     "wiki": WIKI + "Petal"},
    {"term": "Petal", "cat": "Perianth", "image": "petal.png",
     "definition": "A petal is one segment of the corolla.",
     "wiki": WIKI + "Petal"},

    # ---- androecium ----
    {"term": "Androecium", "cat": "Androecium (male)", "image": "androecium.png",
     "definition": "The androecium is the male whorl. It is made of all the stamens.",
     "wiki": WIKI + "Stamen"},
    {"term": "Stamen", "cat": "Androecium (male)", "image": "stamen.png",
     "definition": "A stamen is one male unit. It has a filament and an anther.",
     "wiki": WIKI + "Stamen"},
    {"term": "Filament", "cat": "Androecium (male)", "image": "filament.png",
     "definition": "The filament is the stalk of a stamen. It holds the anther up.",
     "wiki": WIKI + "Stamen"},
    {"term": "Anther", "cat": "Androecium (male)", "image": "anther.png",
     "definition": "The anther is the pollen-bearing tip of a stamen.",
     "wiki": WIKI + "Stamen"},

    # ---- gynoecium ----
    {"term": "Gynoecium", "cat": "Gynoecium (female)", "image": "gynoecium.png",
     "definition": "The gynoecium is the female whorl. It is made of one or more "
                   "carpels.",
     "wiki": WIKI + "Gynoecium"},
    {"term": "Carpel (pistil)", "cat": "Gynoecium (female)", "image": "carpel.png",
     "definition": "A carpel is one female unit. It has an ovary, a style and a "
                   "stigma. A pistil is one carpel or several fused carpels.",
     "wiki": WIKI + "Gynoecium"},
    {"term": "Ovary", "cat": "Gynoecium (female)", "image": "ovary.png",
     "definition": "The ovary is the swollen base of the carpel. It holds the ovules "
                   "and ripens into the fruit.",
     "wiki": WIKI + "Ovary_(botany)"},
    {"term": "Style", "cat": "Gynoecium (female)", "image": "style.png",
     "definition": "The style is the stalk that connects the ovary to the stigma.",
     "wiki": WIKI + "Gynoecium"},
    {"term": "Stigma", "cat": "Gynoecium (female)", "image": "stigma.png",
     "definition": "The stigma is the receptive tip of the carpel. It catches pollen.",
     "wiki": WIKI + "Stigma_(botany)"},

    # ---- inside the ovary ----
    {"term": "Ovule", "cat": "Inside the ovary", "image": "xsec.png",
     "definition": "An ovule sits inside the ovary. After fertilisation it becomes a "
                   "seed.",
     "wiki": WIKI + "Ovule"},
    {"term": "Placenta", "cat": "Inside the ovary", "image": "xsec.png",
     "definition": "The placenta is the tissue inside the ovary where the ovules "
                   "attach.",
     "wiki": WIKI + "Ovary_(botany)"},
    {"term": "Locule", "cat": "Inside the ovary", "image": "xsec.png",
     "definition": "A locule is a chamber inside the ovary. The carpel wall or a "
                   "septum encloses it.",
     "wiki": WIKI + "Locule"},
    {"term": "Septum", "cat": "Inside the ovary", "image": "xsec.png",
     "definition": "A septum is a wall inside the ovary that divides the chambers.",
     "wiki": WIKI + "Ovary_(botany)"},
    {"term": "Placentation", "cat": "Inside the ovary", "image": "xsec.png",
     "definition": "Placentation is the arrangement of the placentas and ovules "
                   "inside the ovary. Common types are axile, parietal, free-central "
                   "and marginal.",
     "wiki": WIKI + "Placentation#In_plants"},

    # ---- symmetry and fusion ----
    {"term": "Actinomorphic", "cat": "Symmetry and fusion", "image": "actinomorphic.png",
     "definition": "An actinomorphic flower is radially symmetric. It can be cut into "
                   "matching halves along many planes.",
     "wiki": WIKI + "Floral_symmetry"},
    {"term": "Zygomorphic", "cat": "Symmetry and fusion", "image": "zygomorphic.png",
     "definition": "A zygomorphic flower is bilaterally symmetric. It has only one "
                   "plane of symmetry.",
     "wiki": WIKI + "Floral_symmetry"},
    {"term": "Sympetalous corolla", "cat": "Symmetry and fusion", "image": "sympetalous.png",
     "definition": "A sympetalous corolla has fused petals that join into a tube or "
                   "bell. A corolla with free petals is polypetalous.",
     "wiki": WIKI + "Petal"},
    {"term": "Apocarpous gynoecium", "cat": "Symmetry and fusion", "image": "apocarpous.png",
     "definition": "An apocarpous gynoecium has separate carpels. When the carpels "
                   "are fused it is syncarpous.",
     "wiki": WIKI + "Gynoecium"},
]

CATEGORIES = ["Whole flower", "Perianth", "Androecium (male)",
              "Gynoecium (female)", "Inside the ovary", "Symmetry and fusion"]
